import { COLOR } from "../theme.types";

/*
  Names generated by https://www.color-name.com/
*/

export const COLOR_AURO_METAL_SAURUS: COLOR = '#68757E';
export const COLOR_BEGONIA: COLOR = '#FF7171';
export const COLOR_BLACK_OLIVE: COLOR = '#3E3E3E';
export const COLOR_BUBBLES: COLOR = '#E7F5FF';
export const COLOR_CHARCOAL: COLOR = '#384A56';
export const COLOR_CHINESE_BLACK: COLOR = '#171717';
export const COLOR_CULTURED: COLOR = '#F5F5F5';
export const COLOR_ELETRIC_INDIGO: COLOR = '#6F11FB';
export const COLOR_GAINSBORO: COLOR = '#DADADA';
export const COLOR_GOLDEN_GATE_BRIDGE: COLOR = '#B73333';
export const COLOR_MEDIUM_SKY_BLUE: COLOR = '#79DDF5';
export const COLOR_ONYX_LIGHT: COLOR = '#363D42';
export const COLOR_ONYX: COLOR = '#32373D';
export const COLOR_PASTEL_BLUE: COLOR = '#ADBDC7';
export const COLOR_PLATINUM: COLOR = '#E8E8E8';
export const COLOR_RAISIN_BLACK: COLOR = '#212121';
export const COLOR_ROMAN_SILVER: COLOR = '#858E94';
export const COLOR_SONIC_SILVER: COLOR = '#717679';
export const COLOR_VIOLET: COLOR = '#9700A1';

export const COLOR_BLACK: COLOR = '#000000';
export const COLOR_BLACK_ALPHA_05: COLOR = 'rgba(0, 0, 0, 0.34)';
export const COLOR_BLACK_ALPHA_34: COLOR = 'rgba(0, 0, 0, 0.05)';

export const COLOR_WHITE: COLOR = '#FFFFFF';
export const COLOR_WHITE_ALPHA_60: COLOR = 'rgba(255, 255, 255, 0.6)';
export const COLOR_WHITE_ALPHA_05: COLOR = 'rgba(255, 255, 255, 0.05)';
