import { COLOR } from '../theme.types';

/*
  Names generated by https://www.color-name.com/
*/

//#region COMMON
export const COLOR_BLACK: COLOR = 'rgb(0, 0, 0)';
export const COLOR_BLACK_ALPHA_10: COLOR = 'rgba(0, 0, 0, 0.1)';

export const COLOR_WHITE: COLOR = 'rgb(255, 255, 255)';
export const COLOR_WHITE_ALPHA_05: COLOR = 'rgba(255, 255, 255, 0.05)';
export const COLOR_WHITE_ALPHA_10: COLOR = 'rgba(255, 255, 255, 0.1)';

export const COLOR_GOLDEN_GATE_BRIDGE: COLOR = '#B73333';
export const COLOR_BEGONIA: COLOR = '#FF7171';
//#endregion

// LIGHT
export const COLOR_CULTURED: COLOR = '#F5F5F5'; // 1

export const COLOR_ELETRIC_INDIGO: COLOR = '#6F11FB'; //2
export const COLOR_ELETRIC_INDIGO_ALPHA_10: COLOR = 'rgba(111, 17, 251, .1)';
export const COLOR_ELETRIC_INDIGO_ALPHA_20: COLOR = 'rgba(111, 17, 251, .2)';
export const COLOR_ELETRIC_INDIGO_ALPHA_50: COLOR = 'rgba(111, 17, 251, .5)';

export const COLOR_ONYX_LIGHT: COLOR = '#363D42'; //3
export const COLOR_ONYX_LIGHT_ALPHA_70: COLOR = 'rgba(54, 61, 66, .7)';

export const COLOR_VIOLET: COLOR = '#9700A1'; //4

// DARK

export const COLOR_ONYX: COLOR = '#32373D'; //1

export const COLOR_LIGHT_SILVER: COLOR = '#D6D7D8' //2
export const COLOR_SILVER_SAND: COLOR = '#C1C3C4' //3
export const COLOR_SILVER_SAND_ALPHA_70: COLOR = '#rgba(193, 195, 196, .7)'

export const COLOR_DARK_JUNGLE_GREEN: COLOR = '#1e2124' //4

export const COLOR_MEDIUM_SKY_BLUE: COLOR = '#79DDF5'; //5
export const COLOR_MEDIUM_SKY_BLUE_ALPHA_10: COLOR = 'rgba(121, 221, 245, .1)';
export const COLOR_MEDIUM_SKY_BLUE_ALPHA_20: COLOR = 'rgba(121, 221, 245, .2)';
export const COLOR_MEDIUM_SKY_BLUE_ALPHA_50: COLOR = 'rgba(121, 221, 245, .5)';
export const COLOR_MEDIUM_SKY_BLUE_ALPHA_70: COLOR = 'rgba(121, 221, 245, .7)';




// OTHER
// export const COLOR_BUBBLES: COLOR = '#E7F5FF';

// export const COLOR_PASTEL_BLUE: COLOR = '#ADBDC7';
// export const COLOR_CHINESE_BLACK: COLOR = '#171717';

// export const COLOR_GAINSBORO: COLOR = '#DADADA';
// export const COLOR_ROMAN_SILVER: COLOR = '#858E94';

// export const COLOR_AURO_METAL_SAURUS: COLOR = '#68757E';
// export const COLOR_BLACK_OLIVE: COLOR = '#3E3E3E';
// export const COLOR_CHARCOAL: COLOR = '#384A56';

// export const COLOR_PLATINUM: COLOR = '#E8E8E8';
// export const COLOR_RAISIN_BLACK: COLOR = '#212121';
// export const COLOR_SONIC_SILVER: COLOR = '#717679';
