import { COLOR } from '../theme.types';

/*
  Names generated by https://www.color-name.com/
*/

//COMMON
export const COLOR_BLACK: COLOR = 'rgb(0, 0, 0)';
export const COLOR_BLACK_ALPHA_10: COLOR = 'rgba(0, 0, 0, 0.1)';

export const COLOR_WHITE: COLOR = 'rgb(255, 255, 255)';
export const COLOR_WHITE_ALPHA_05: COLOR = 'rgba(255, 255, 255, 0.05)';
export const COLOR_WHITE_ALPHA_10: COLOR = 'rgba(255, 255, 255, 0.1)';
